# 参考文档
# https://docs.projectdiscovery.io/tools/nuclei/running#nuclei-config
# https://github.com/projectdiscovery/nuclei/issues/472
# https://docs.projectdiscovery.io/tools/nuclei/authenticated-scans#static-authentication

# 连接控制
## 设置代理
#proxy: 'http://127.0.0.1:8080'
## 超时
timeout: 5
no-max-host-error: true

# 所有 HTTP 请求中要包含的标头
## 便于运营识别是内外部扫描流量
header:
  - 'X-BugBounty-Hacker: Hackerone'

# 认证文件
## 包含 nuclei 认证扫描密钥的配置文件路径
#secret-file: 'Secret.yaml'
## 预先从密钥文件中获取密钥
#prefetch-secrets: true

# 速率限制配置
## 每个模板可并行分析的最大主机数（默认 25）
bulk-size: 50
## 并行执行的最大模板数量（默认：25）
concurrency: 50
## 每秒最大请求量（默认：150）
rate-limit: 500

# 更新控制
## 更新模板
update-templates: false
## 禁用 nuclei 程序与模板更新
disable-update-check: true

# 反连平台控制
## 禁用反连检测平台，同时排除基于反连检测的模板
## 反连检测的误报率相对较高，并且内网环境下不适用，可按需启用
no-interactsh: true

# pd 云平台控制
## 关闭云上传
cloud-upload: false

# 终端显示控制
## 关闭终端输出
silent: false
## 显示扫描进度统计情况
stats: false
#verbose: true

# export
#markdown-export: markdown-export
#report-db: report-db

# UNCOVER引擎:
# uncover: false
# uncover-query: 'app=nacos'
# uncover-engine: fofa
# uncover-limit: 10000

# 扫描模板控制
## 特定场合下，可以通过指定模板目录，来指定扫描模板
# templates: 'D:\\My-nuclei-Templates'
# include-rr: false
# json: false
# no-meta: false
# update-directory: $HOME/

# 基于目录的模板执行
# templates:
#   - cves/
#   - vulnerabilities/
#   - misconfiguration/

# 基于标签的模板执行
# tags: exposures,cve

# 模板过滤器
# tags: exposures,cve
# author: geeknik,pikpikcu,dhiyaneshdk
# severity: critical,high,medium
severity: critical,high,medium
include-tags:
  - api
  - exposure
include-templates:
  - http/exposures/apis
  - http/exposures/apis/swagger-api.yaml
  - http/technologies/fingerprinthub-web-fingerprints.yaml
# 模板拒绝列表
exclude-tags: 
  - xss
  - ssh
  - miscellaneous
  - cnvd
  - dos
  - osint
  - c2
  - malware
  - udp
  - enum
  - bokbot
  - trojan 
  - creds-stuffing
  - token-spray
  - local
  - wordpress
  - dvwa
  - network
  - dns
  - ssl

exclude-templates: # Template based exclusion
  - config
  - file
  - profiles
  - dns
  - ssl
  - javascript/default-logins/
  - network/default-login/
  - http/default-logins/
  - dns/caa-fingerprint.yaml
  - dns/nameserver-fingerprint.yaml
  - http/miscellaneous/external-service-interaction.yaml
  - http/miscellaneous/google-floc-disabled.yaml
  - http/miscellaneous/old-copyright.yaml
  - http/miscellaneous/rdap-whois.yaml
  - http/misconfiguration/http-missing-security-headers.yaml
  - http/misconfiguration/http-missing-security-headers.yaml
  - http/misconfiguration/httponly-cookie-detect.yaml
  - http/technologies/spring-detect.yaml
  - http/technologies/tech-detect.yaml
  - http/vulnerabilities/generic/request-based-interaction.yaml
  - javascript/detection/ssh-auth-methods.yaml
  - javascript/enumeration/ssh-cbc-mode-ciphers.yaml
  - javascript/enumeration/ssh-diffie-hellman-logjam.yaml
  - javascript/enumeration/ssh-password-auth.yaml
  - javascript/enumeration/ssh-server-enumeration.yaml
  - javascript/enumeration/ssh-sha1-hmac-algo.yaml
  - javascript/enumeration/ssh-weak-algo-supported.yaml
  - javascript/enumeration/ssh-weak-mac-algo.yaml
  - javascript/enumeration/ssh-weakkey-exchange-algo.yaml
  - ssl/deprecated-tls.yaml
  - ssl/detect-ssl-issuer.yaml
  - ssl/tls-version.yaml
  - http/cves/2000/
  - http/cves/2001/
  - http/cves/2002/
  - http/cves/2004/
  - http/cves/2005/
  - http/cves/2006/
  - http/cves/2007/
  - http/cves/2008/
  - http/cves/2009/
  - http/cves/2010/
  - http/cves/2011/
  - http/cves/2012/
  - http/cves/2013/
  - http/cves/2014/
  - http/cves/2015/
  - http/cves/2016/
  - http/cves/2017/
  - http/cves/2018/
  - http/cves/2019/
  - http/cves/2020/
  - http/cves/2021/
  - http/cves/2022/